name: Publish next package

on:
  release:
    types: [created]

jobs:
  deploy:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install modules
        run: bun install --immutable

      - name: Run lint scripts
        run: bun run lint:ci

      - name: Verify no files have changed after auto-fix
        run: git diff -- ":(exclude)example/*" --exit-code HEAD

      - name: Prepare module
        run: yarn prepare

      - name: Configure npm for publishing
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - run: npm publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
